import type { Metadata } from 'next'
import { Providers } from './providers'
import { Box, ColorModeScript } from '@chakra-ui/react'
import { theme } from './theme'
import Navbar from '@/components/Navbar'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body >
        <ColorModeScript initialColorMode={theme.config.initialColorMode} />
        <Providers>
          <Navbar />
          <Box
            mt={8}
            mx="auto"
            maxW={"800px"}
            w="100%"
          >
            {children}
          </Box>
        </Providers>
      </body>
    </html>
  )
}
